# Pandas Basics

DS 2023 | Communicating with Data

## Overiew

This notebook covers some of the basics of using Pandas.

It is meant to get you acquainted with how Pandas does some common data operations, not to provide in depth coverage of the library.

Basic operations include filtering and selecting data from an existing dataset.

## Set Up

In this notebook, We will use the `nycflights13` dataset, which contains every flight that departed from a New York City airport in 2013. The data comes from the US Bureau of Transportation Statistics.

Here is a **data dictionary** for the dataset:

| Variable Name | Data Type | Description |
|---|---|---|
| year, month, day | Integer | Date of departure. |
| dep_time, arr_time | Integer | Actual departure and arrival times (Format: Local time, HHMM or HMM). Missing values (NA) represent canceled flights. |
| sched_dep_time, sched_arr_time | Integer | Scheduled departure and arrival times (Format: Local time, HHMM or HMM). |
| dep_delay, arr_delay | Float | Departure and arrival delays, measured in minutes. Negative times represent early departures/arrivals. |
| carrier | String | Two-letter airline carrier abbreviation (maps to the airlines table). |
| flight | Integer | Flight number. |
| tailnum | String | Aircraft tail number (maps to the planes table). Missing values (NA) represent canceled flights. |
| origin | String | Origin airport code (EWR, JFK, or LGA; maps to airports and weather). |
| dest | String | Destination airport code (maps to airports). |
| air_time | Float | Amount of time spent in the air, measured in minutes. |
| distance | Float | Distance between origin and destination airports, measured in miles. |
| hour, minute | Float | Scheduled departure time broken down into hour and minute components. |
| time_hour | datetime | Scheduled date and time of the flight formatted as a timestamp (YYYY-MM-DD HH:MM:SS). Used for joining directly with the weather table. |

If you are currently writing code, let me know if you need help with a specific programming language (like R or Python) or a particular data manipulation query (such as calculating average delays by carrier).

In [3]:
import pandas as pd

flight_data_url = "https://virginia.box.com/shared/static/hby5hxuvurkmatdxgy0p1ua7oftwl6i9.csv"
flights = pd.read_csv(flight_data_url)

## Inspect the data

This dataset contains all $336,776$ flights that departed New York City in 2013.

In [4]:
flights

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336772,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00
336772,336773,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00
336773,336774,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00
336774,336775,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00
336775,336776,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00

### The `info` method

The `.info()` method gives a compact structural overview: column names, data types, and how many non-missing values each column has.

This gives us information on the name and data type of each column, as well as how many non-null values are in each column.

In [5]:
flights.info()

<class 'pandas.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 20 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0      336776 non-null  int64
 1   year            336776 non-null  int64
 2   month           336776 non-null  int64
 3   day             336776 non-null  int64
 4   dep_time        328521 non-null  float64
 5   sched_dep_time  336776 non-null  int64
 6   dep_delay       328521 non-null  float64
 7   arr_time        328063 non-null  float64
 8   sched_arr_time  336776 non-null  int64
 9   arr_delay       327346 non-null  float64
 10  carrier         336776 non-null  str
 11  flight          336776 non-null  int64
 12  tailnum         334264 non-null  str
 13  origin          336776 non-null  str
 14  dest            336776 non-null  str
 15  air_time        327346 non-null  float64
 16  distance        336776 non-null  int64
 17  hour            336776 non-null  int64
 18  minute          336776 non-null  int64
 19  time_hour       336776 non-null  str
dtypes: float64(5), int64(10), str(5)
memory usage: 51.4 MB

> [!note] Pandas data types (`Dtype`) like `int64`, `float64`, `object` (usually strings), and `datetime64` matter for the same reason data types always do: the operations you can perform on a column depend on its type.

### A quick note on Pandas' methods

Most of Pandas' core operations are **methods**. 

> [!tip] Remember that in object-oreinted parlance a method is a function attached to an object. The object in most cases is the dataframe. In some cases, though, Pandas' methods are attached to the Pandas object itself, i.e. `pd`.

These are called with `.` directly on the object, in this case `flights`.

For example, to get the top rows in a dataframe, we call the `.head()` method.

In [6]:
flights.head()

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00

## How many rows and columns are in the dataframe?

The number of rows and columns in a dataframe is called its **shape**.

You access this information by calling the dataframe's shape attribute, like so:

In [10]:
flights.shape

(336776, 20)

Note that it returns a tuple.

If you were only interested in findout out how many rows are in the dataset, you can do this:

In [11]:
flights.shape[0]

336776

Or, you could use Python's `len()` function, which works on any list-like object:

In [12]:
len(flights)

336776

> [!caution] The shape returned by `.shape` will show the number of columns in the dataframe _excluding_ any index columns.

## Are the data tidy?

Always begin by asking this question.

If they data are not tidy, what shape are they in (literally)?

Does the dataset need to be reshaped in any way?

If they are tidy, what is the unit of observation?

In this case, the dataset is tidy and the unit of obseration is the specific flight -- the taking off and landing of a specific airplane.

## Classify the columns

The next thing to do is identify the column types.

Are there any identifiers? Groupers? Measurements?

Are there any redundant columns? These are columns that repeat data in other columns.

Are there any analytical columns? These are columns that are computed from one or more other columns.

### The `columns` attribute

Here, we grab the list of columns from the dataset using the `columns` attribute of the dataframe.

Using the information we got from `.info()`, we can identify the column uses.

Note we are using the column number offsets to combine slices of the column list to create our new lists.

In [7]:
cols = list(flights.columns)
cols

['Unnamed: 0',
 'year',
 'month',
 'day',
 'dep_time',
 'sched_dep_time',
 'dep_delay',
 'arr_time',
 'sched_arr_time',
 'arr_delay',
 'carrier',
 'flight',
 'tailnum',
 'origin',
 'dest',
 'air_time',
 'distance',
 'hour',
 'minute',
 'time_hour']

In [8]:
group_cols = cols[1:4] + cols[10:15] + cols[17:19]
group_cols

['year',
 'month',
 'day',
 'carrier',
 'flight',
 'tailnum',
 'origin',
 'dest',
 'hour',
 'minute']

In [9]:
measure_cols = cols[4:10] + cols[15:17]
measure_cols

['dep_time',
 'sched_dep_time',
 'dep_delay',
 'arr_time',
 'sched_arr_time',
 'arr_delay',
 'air_time',
 'distance']

There are no identifying columns, and there are two redundant ones: `time_hour` and `Unnamed: 0`.

The `Unnamed: 0` column is an artifact of the import process. It gave this name to the unnamed first column in the CSV file, which clearly stands for the row number.

> [!tip] To avoid this kind of spurious column naming, you can tell Pandas to treat the first column as an index by setting the argument `index_col` to $0$ in the `read_csv` function:
> ```python
> flights = pd.read_csv(flight_data_url, index_col=0)
> ```
> To see how this works, try replacing the line of code above where we import the dataset with this one.

## Filtering rows

One of the most important operations to perform on a dataframe is filtering.

Filtering grabs a subset of rows based on some specified conditions.

> [!important] Filtering is a **row-wise operation**: We use it to extract a subset of **rows** that meet certain conditions.

For example, we may want to see only rows for a certain year and month.

### The `query` method 

We can use `.query()` to do this. It works by passing a condition expressed as a string. 

For example, to see all flights for February 2013, we would do this:

In [69]:
flights.query("year == 2013 & month == 2")

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,gain,speed
111296,111297,2013,2,1,456.0,500,-4.0,652.0,648,4.0,...,N197UW,EWR,CLT,98.0,529,5,0,2013-02-01 05:00:00,-8.0,323.877551
111297,111298,2013,2,1,520.0,525,-5.0,816.0,820,-4.0,...,N24211,EWR,IAH,209.0,1400,5,25,2013-02-01 05:00:00,-1.0,401.913876
111298,111299,2013,2,1,527.0,530,-3.0,837.0,829,8.0,...,N470UA,LGA,IAH,233.0,1416,5,30,2013-02-01 05:00:00,-11.0,364.635193
111299,111300,2013,2,1,532.0,540,-8.0,1007.0,1017,-10.0,...,N554JB,JFK,BQN,195.0,1576,5,40,2013-02-01 05:00:00,2.0,484.923077
111300,111301,2013,2,1,540.0,540,0.0,859.0,850,9.0,...,N615AA,JFK,MIA,169.0,1089,5,40,2013-02-01 05:00:00,-9.0,386.627219
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136242,136243,2013,2,28,NaN,850,NaN,NaN,1035,NaN,...,N737MQ,LGA,CLE,NaN,419,8,50,2013-02-28 08:00:00,NaN,NaN
136243,136244,2013,2,28,NaN,905,NaN,NaN,1115,NaN,...,N722MQ,LGA,DTW,NaN,502,9,5,2013-02-28 09:00:00,NaN,NaN
136244,136245,2013,2,28,NaN,1115,NaN,NaN,1310,NaN,...,N725MQ,LGA,CMH,NaN,479,11,15,2013-02-28 11:00:00,NaN,NaN
136245,136246,2013,2,28,NaN,830,NaN,NaN,1205,NaN,...,NaN,EWR,SFO,NaN,2565,8,30,2013-02-28 08:00:00,NaN,NaN
136246,136247,2013,2,28,NaN,840,NaN,NaN,1147,NaN,...,NaN,JFK,LAX,NaN,2475,8,40,2013-02-28 08:00:00,NaN,NaN

Here is a query for flights delayed more than 120 minutes:

In [111]:
flights.query("dep_delay > 120")

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,gain,speed
151,152,2013,1,1,848.0,1835,853.0,1001.0,1950,851.0,...,N942MQ,JFK,BWI,41.0,184,18,35,2013-01-01 18:00:00,2.0,269.268293
218,219,2013,1,1,957.0,733,144.0,1056.0,853,123.0,...,N534UA,EWR,BOS,37.0,200,7,33,2013-01-01 07:00:00,21.0,324.324324
268,269,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,...,N76502,LGA,IAH,248.0,1416,9,0,2013-01-01 09:00:00,-11.0,342.580645
491,492,2013,1,1,1540.0,1338,122.0,2020.0,1825,115.0,...,N570JB,JFK,SJU,193.0,1598,13,38,2013-01-01 13:00:00,7.0,496.787565
649,650,2013,1,1,1815.0,1325,290.0,2120.0,1542,338.0,...,N17185,EWR,OMA,213.0,1134,13,25,2013-01-01 13:00:00,-48.0,319.436620
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336579,336580,2013,9,30,1823.0,1545,158.0,1934.0,1733,121.0,...,N916XJ,JFK,BNA,95.0,765,15,45,2013-09-30 15:00:00,37.0,483.157895
336668,336669,2013,9,30,1951.0,1649,182.0,2157.0,1903,174.0,...,N13988,EWR,SAV,95.0,708,16,49,2013-09-30 16:00:00,8.0,447.157895
336724,336725,2013,9,30,2053.0,1815,158.0,2310.0,2054,136.0,...,N600QX,EWR,ATL,91.0,746,18,15,2013-09-30 18:00:00,22.0,491.868132
336757,336758,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,...,N906XJ,JFK,BUF,50.0,301,18,45,2013-09-30 18:00:00,0.0,361.200000
336763,336764,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,...,N804JB,JFK,MCO,123.0,944,20,1,2013-09-30 20:00:00,24.0,460.487805

### The indexer method

You also filter by supplying the two expressions directly to the dataframe's **indexer**, which you can access by using two square brackets at the end of the variable name, e.g. `flights[]`.

Note that the two boolean expressions are enclosed in parentheses.

In [164]:
flights[(flights['year'] == 2013) & (flights['month'] == 2)]

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
111296,111297,2013,2,1,456.0,500,-4.0,652.0,648,4.0,US,1117,N197UW,EWR,CLT,98.0,529,5,0,2013-02-01 05:00:00
111297,111298,2013,2,1,520.0,525,-5.0,816.0,820,-4.0,UA,1018,N24211,EWR,IAH,209.0,1400,5,25,2013-02-01 05:00:00
111298,111299,2013,2,1,527.0,530,-3.0,837.0,829,8.0,UA,650,N470UA,LGA,IAH,233.0,1416,5,30,2013-02-01 05:00:00
111299,111300,2013,2,1,532.0,540,-8.0,1007.0,1017,-10.0,B6,725,N554JB,JFK,BQN,195.0,1576,5,40,2013-02-01 05:00:00
111300,111301,2013,2,1,540.0,540,0.0,859.0,850,9.0,AA,1141,N615AA,JFK,MIA,169.0,1089,5,40,2013-02-01 05:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136242,136243,2013,2,28,NaN,850,NaN,NaN,1035,NaN,MQ,4558,N737MQ,LGA,CLE,NaN,419,8,50,2013-02-28 08:00:00
136243,136244,2013,2,28,NaN,905,NaN,NaN,1115,NaN,MQ,4478,N722MQ,LGA,DTW,NaN,502,9,5,2013-02-28 09:00:00
136244,136245,2013,2,28,NaN,1115,NaN,NaN,1310,NaN,MQ,4485,N725MQ,LGA,CMH,NaN,479,11,15,2013-02-28 11:00:00
136245,136246,2013,2,28,NaN,830,NaN,NaN,1205,NaN,UA,1480,NaN,EWR,SFO,NaN,2565,8,30,2013-02-28 08:00:00
136246,136247,2013,2,28,NaN,840,NaN,NaN,1147,NaN,UA,443,NaN,JFK,LAX,NaN,2475,8,40,2013-02-28 08:00:00

### The `loc` accessor method

You can also query by using Pandas' `loc` accessor method to do queries.

In [112]:
flights.loc[flights['dep_time'] > 120]

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,gain,speed
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,...,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,-9.0,370.044053
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,...,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,-16.0,374.273128
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,...,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,-31.0,408.375000
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,...,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,17.0,516.721311
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,...,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,19.0,394.137931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336765,336766,2013,9,30,2240.0,2245,-5.0,2334.0,2351,-17.0,...,N354JB,JFK,SYR,41.0,209,22,45,2013-09-30 22:00:00,12.0,305.853659
336766,336767,2013,9,30,2240.0,2250,-10.0,2347.0,7,-20.0,...,N281JB,JFK,BUF,52.0,301,22,50,2013-09-30 22:00:00,10.0,347.307692
336767,336768,2013,9,30,2241.0,2246,-5.0,2345.0,1,-16.0,...,N346JB,JFK,ROC,47.0,264,22,46,2013-09-30 22:00:00,11.0,337.021277
336768,336769,2013,9,30,2307.0,2255,12.0,2359.0,2358,1.0,...,N565JB,JFK,BOS,33.0,187,22,55,2013-09-30 22:00:00,11.0,340.000000
336769,336770,2013,9,30,2349.0,2359,-10.0,325.0,350,-25.0,...,N516JB,JFK,PSE,196.0,1617,23,59,2013-09-30 23:00:00,15.0,495.000000

## Sorting rows with `sort_values`

The method `.sort_values()` changes the order of rows based on the value of one or more columns. 

It takes a list of column names, or a single column name, to sort by.

The `ascending` argument determines the resulting sort order, whether from least to greatest (`asending = True`) or not. The default value is `True`, so if we want reverse sort order we set it to `False`.

In [113]:
flights.sort_values('dep_delay', ascending=False)

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,gain,speed
7072,7073,2013,1,9,641.0,900,1301.0,1242.0,1530,1272.0,...,N384HA,JFK,HNL,640.0,4983,9,0,2013-01-09 09:00:00,29.0,467.156250
235778,235779,2013,6,15,1432.0,1935,1137.0,1607.0,2120,1127.0,...,N504MQ,JFK,CMH,74.0,483,19,35,2013-06-15 19:00:00,10.0,391.621622
8239,8240,2013,1,10,1121.0,1635,1126.0,1239.0,1810,1109.0,...,N517MQ,EWR,ORD,111.0,719,16,35,2013-01-10 16:00:00,17.0,388.648649
327043,327044,2013,9,20,1139.0,1845,1014.0,1457.0,2210,1007.0,...,N338AA,JFK,SFO,354.0,2586,18,45,2013-09-20 18:00:00,7.0,438.305085
270376,270377,2013,7,22,845.0,1600,1005.0,1044.0,1815,989.0,...,N665MQ,JFK,CVG,96.0,589,16,0,2013-07-22 16:00:00,16.0,368.125000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336772,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,...,NaN,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00,NaN,NaN
336772,336773,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,...,NaN,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00,NaN,NaN
336773,336774,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,...,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00,NaN,NaN
336774,336775,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,...,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00,NaN,NaN
336775,336776,2013,9,30,NaN,840,NaN,NaN,1020,NaN,...,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00,NaN,NaN

Note that the number of rows hasn't changed. Sorting rearranges the data, it doesn't filter it.

## Removing duplicate rows with `drop_duplicates`

`.drop_duplicates()` finds unique rows in a dataset.

In [54]:
flights1 = flights.drop_duplicates()

We can compare the lenghts of the two dataframes to see if there are any duplicates.

In [135]:
len(flights) == len(flights1)

True

Turns out there aren't.

## Creating new columns

You can create new columns by naming them in the indexer and then assigning a value to them.

Let's compute the `gain` (how much time a delayed flight made up in the air) and the `speed` in miles per hour:

In [62]:
flights['gain'] = flights['dep_delay'] - flights['arr_delay']
flights['speed'] = flights["distance"] / flights["air_time"] * 60
flights

,Unnamed: 0,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,...,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,gain,speed
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,...,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,-9.0,370.044053
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,...,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,-16.0,374.273128
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,...,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,-31.0,408.375000
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,...,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,17.0,516.721311
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,...,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,19.0,394.137931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336772,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,...,NaN,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00,NaN,NaN
336772,336773,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,...,NaN,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00,NaN,NaN
336773,336774,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,...,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00,NaN,NaN
336774,336775,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,...,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00,NaN,NaN
336775,336776,2013,9,30,NaN,840,NaN,NaN,1020,NaN,...,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00,NaN,NaN

> [!note] These new columns are what we have been called "analytical" columns. They are direct transforamtions of the data and don't add any new empirical information to the dataset.

## Selecting columns

Another important operation to perform on a dataframe is to select a subset of columns.

Sometimes you do this because there are too many columns to see on one page. Other times, you want to zoom in on a few columns for exploratory purposes.

> [!important] Selecting is a **column-wise** operation. We use it to select a subset of columns from the dataframe.

To select columns, we just pass a list of column names to the dataframe.

In [63]:
flights[["year", "month", "day"]]

        year  month  day
0       2013      1    1
1       2013      1    1
2       2013      1    1
3       2013      1    1
4       2013      1    1
...      ...    ...  ...
336771  2013      9   30
336772  2013      9   30
336773  2013      9   30
336774  2013      9   30
336775  2013      9   30

[336776 rows x 3 columns]

Note that we can pass a list of columns in a different order than how they appear in the dataframe.

In [126]:
flights[["year", "day", "month"]]

        year  day  month
0       2013    1      1
1       2013    1      1
2       2013    1      1
3       2013    1      1
4       2013    1      1
...      ...  ...    ...
336771  2013   30      9
336772  2013   30      9
336773  2013   30      9
336774  2013   30      9
336775  2013   30      9

[336776 rows x 3 columns]

We can also select a *range* of columns by position with `loc` method.

The `:` in the expression below means all rows &mdash; we'll look at this function more below.

In [67]:
flights.loc[:, "year":"day"]

        year  month  day
0       2013      1    1
1       2013      1    1
2       2013      1    1
3       2013      1    1
4       2013      1    1
...      ...    ...  ...
336771  2013      9   30
336772  2013      9   30
336773  2013      9   30
336774  2013      9   30
336775  2013      9   30

[336776 rows x 3 columns]

We can use our column lists from above to select, too.

In [107]:
flights[group_cols]

        year  month  day  hour  minute carrier  flight tailnum origin dest
0       2013      1    1     5      15      UA    1545  N14228    EWR  IAH
1       2013      1    1     5      29      UA    1714  N24211    LGA  IAH
2       2013      1    1     5      40      AA    1141  N619AA    JFK  MIA
3       2013      1    1     5      45      B6     725  N804JB    JFK  BQN
4       2013      1    1     6       0      DL     461  N668DN    LGA  ATL
...      ...    ...  ...   ...     ...     ...     ...     ...    ...  ...
336771  2013      9   30    14      55      9E    3393     NaN    JFK  DCA
336772  2013      9   30    22       0      9E    3525     NaN    LGA  SYR
336773  2013      9   30    12      10      MQ    3461  N535MQ    LGA  BNA
336774  2013      9   30    11      59      MQ    3572  N511MQ    LGA  CLE
336775  2013      9   30     8      40      MQ    3531  N839MQ    LGA  RDU

[336776 rows x 10 columns]

In [108]:
flights[measure_cols]

,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,air_time,distance
0,517.0,515,2.0,830.0,819,11.0,227.0,1400
1,533.0,529,4.0,850.0,830,20.0,227.0,1416
2,542.0,540,2.0,923.0,850,33.0,160.0,1089
3,544.0,545,-1.0,1004.0,1022,-18.0,183.0,1576
4,554.0,600,-6.0,812.0,837,-25.0,116.0,762
...,...,...,...,...,...,...,...,...
336771,NaN,1455,NaN,NaN,1634,NaN,NaN,213
336772,NaN,2200,NaN,NaN,2312,NaN,NaN,198
336773,NaN,1210,NaN,NaN,1330,NaN,NaN,764
336774,NaN,1159,NaN,NaN,1344,NaN,NaN,419
336775,NaN,840,NaN,NaN,1020,NaN,NaN,431

## Combining filtering and selecting with `loc`

With the `loc` method, you can combine filtering and selecting.

- In the **first argument**, you can put a **filtering** expression. This is usually a boolean expression applied to one or more columns in the dataframe. 

- In the **second argument**, you can put a **selecting** expression. The is usually a list of columns names.

Think of it this way:

```python
df.loc[rowwise_expression, columnwise_expresson]
```

For example:

In [137]:
flights.loc[flights.month == 1, ['dep_time','dep_delay']]

       dep_time  dep_delay
0         517.0        2.0
1         533.0        4.0
2         542.0        2.0
3         544.0       -1.0
4         554.0       -6.0
...         ...        ...
26999       NaN        NaN
27000       NaN        NaN
27001       NaN        NaN
27002       NaN        NaN
27003       NaN        NaN

[27004 rows x 2 columns]

## Computing stats

The whole point of a dataframe is to be able to compute statistical and other mathematical properties from the data.

Here are a couple of quick things you can do.

### Get the number of values in a column or combination of columns with `value_counts`

You can use `value_counts()` to quickly count the number of rows associated with one or more columns:

In [13]:
flights.value_counts('carrier')

carrier
UA    58665
B6    54635
EV    54173
DL    48110
AA    32729
MQ    26397
US    20536
9E    18460
WN    12275
VX     5162
FL     3260
AS      714
F9      685
YV      601
HA      342
OO       32
Name: count, dtype: int64

In [18]:
flights.value_counts(['origin','dest'])

origin  dest
JFK     LAX     11262
LGA     ATL     10263
        ORD      8857
JFK     SFO      8204
LGA     CLT      6168
                ...
JFK     MEM         1
        STL         1
LGA     LEX         1
JFK     BHM         1
EWR     LGA         1
Name: count, Length: 224, dtype: int64

Note that `value_counts` returns a series , not a dataframe.

If want a dataframe, we can use the `.to_frame()` method.

In [30]:
flights.value_counts(['origin','dest']).to_frame('n')

                 n
origin dest
JFK    LAX   11262
LGA    ATL   10263
       ORD    8857
JFK    SFO    8204
LGA    CLT    6168
...            ...
JFK    MEM       1
       STL       1
LGA    LEX       1
JFK    BHM       1
EWR    LGA       1

[224 rows x 1 columns]

Note also the `.value_counts()` returns a series with an index for the counted columns.

When we have at least two grouping columns in the index, unstack the results, since the count is a measurement.

Here we see a wide table showing the top 20 most frequent origin and destination combinations.

In [34]:
flights.value_counts(['origin','dest']).head(20).unstack(fill_value=0)

dest,LAX,ATL,ORD,SFO,CLT,BOS,MIA,MCO,DTW,DFW,SJU,DCA
origin,,,,,,,,,,,,
EWR,4912,5022,6100,5127,5026,5327,0,4941,0,0,0,0
LGA,0,10263,8857,0,6168,4283,5781,0,5040,4858,0,4716
JFK,11262,0,0,8204,0,5898,0,5464,0,0,4752,0

### Computing aggregate values

You can compute aggregate values in many ways in Pandas. Here are two of the most common.

One is to just apply the aggregate function to one or more columns.

Here we get the mean value of each of our measurement columns.

In [65]:
flights[measure_cols].mean()

dep_time          1349.109947
sched_dep_time    1344.254840
dep_delay           12.639070
arr_time          1502.054999
sched_arr_time    1536.380220
arr_delay            6.895377
air_time           150.686460
distance          1039.912604
dtype: float64

We can also pass the aggregation funcfion name to the `.agg()` method.

In [66]:
flights[measure_cols].agg('mean')

dep_time          1349.109947
sched_dep_time    1344.254840
dep_delay           12.639070
arr_time          1502.054999
sched_arr_time    1536.380220
arr_delay            6.895377
air_time           150.686460
distance          1039.912604
dtype: float64

The `.agg()` method has the advantage of being able to take more than one function.

Here we get the mean, median, and standard deviation.

In [54]:
flights[measure_cols].agg(['mean','median','std'])

,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,air_time,distance
mean,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,150.686460,1039.912604
median,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,129.000000,872.000000
std,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,93.688305,733.233033

We can transpose the table with the `.T` operator to turn the columns into observations.

In [53]:
flights[measure_cols].agg(['mean','median','std']).T

                       mean  median         std
dep_time        1349.109947  1401.0  488.281791
sched_dep_time  1344.254840  1359.0  467.335756
dep_delay         12.639070    -2.0   40.210061
arr_time        1502.054999  1535.0  533.264132
sched_arr_time  1536.380220  1556.0  497.457142
arr_delay          6.895377    -5.0   44.633292
air_time         150.686460   129.0   93.688305
distance        1039.912604   872.0  733.233033

### Using `.groupby()`

We can also use the `.groupby()` method to compute joint aggregate values on combinations of columns.

Here we get the mean values for all of our measure columns for each carrier to each airport.

In [62]:
flights.groupby(['carrier','dest'])[measure_cols].mean()

                 dep_time  sched_dep_time  dep_delay     arr_time  \
carrier dest
9E      ATL    636.842105      635.847458   0.964912   891.464286
        AUS   1694.000000     1655.000000  19.000000  2005.500000
        AVL    974.300000      976.900000  -2.600000  1183.100000
        BGR   2233.000000     2159.000000  34.000000          NaN
        BNA   1588.418502     1563.071730  19.092511  1751.612832
...                   ...             ...        ...          ...
WN      PHX   1298.359155     1258.851508  20.154930  1579.807512
        STL   1265.981379     1240.653506  17.522759  1427.097999
YV      CLT   1567.868217     1541.975177  17.484496  1763.701550
        IAD   1633.569892     1605.090032  21.010753  1762.151079
        PHL   1532.500000     1535.000000  -2.500000  1655.625000

              sched_arr_time  arr_delay    air_time     distance
carrier dest
9E      ATL       875.915254   0.857143  120.107143   759.050847
        AUS      2029.000000  -3.500000  222.000000  1521.000000
        AVL      1195.200000 -12.100000   92.200000   599.000000
        BGR      2327.000000        NaN         NaN   378.000000
        BNA      1728.601266   9.285398  115.785398   764.767932
...                      ...        ...         ...          ...
WN      PHX      1553.573086  14.016471  297.588235  2133.000000
        STL      1414.812798  10.225138  132.798343   880.473792
YV      CLT      1754.709220  12.864341   85.112403   544.000000
        IAD      1734.305466  18.917266   48.514388   229.000000
        PHL      1700.000000 -14.375000   39.625000    96.000000

[314 rows x 8 columns]

Note that `.groupby()` also returns a series with an index.

In this case, we can unstack the results on any of our aggregate measures, like so:

In [64]:
flights.groupby(['carrier','dest'])['dep_delay'].mean().unstack(fill_value=0).style.format(precision=0)

## Chaining it all together

You've now seen several individual operations.

It is possible to combine these operations.

For example, if you wanted to find the fastest flights to Charlottesville's CHO airport: you need to combine filtering, creating a new column, selecting columns, and sorting. 

All in one pipeline:

In [138]:
flights.query('dest == "CHO"')\
    .groupby(["year", "month", "day"])\
    .agg(arr_delay=("arr_delay", "mean"))\
    .reset_index()\
    .head(10)

   year  month  day  arr_delay
0  2013      3    1      -14.0
1  2013      3    3       23.0
2  2013      3    4       12.0
3  2013      3    5        NaN
4  2013      3    6        NaN
5  2013      3    7       -5.0
6  2013      3    8      228.0
7  2013      3   10       30.0
8  2013      3   11       -3.0
9  2013      3   12      105.0

Note the use of backslashes. These allow us to write a single Python expression over multiple lines.

Instead of using backslashes, we can just wrap everything in parentheses.

In [131]:
(
    flights
    .query('dest == "CHO"')
    .groupby(["year", "month", "day"])
    .agg(arr_delay=("arr_delay", "mean"))
    .reset_index()
    .head()
)

   year  month  day  arr_delay
0  2013      3    1      -14.0
1  2013      3    3       23.0
2  2013      3    4       12.0
3  2013      3    5        NaN
4  2013      3    6        NaN

Finally, here is the same set of operations using the indexer syntax.

In [143]:
(
    flights[flights['dest'] == 'CHO']
    .groupby(["year", "month", "day"])['arr_delay']
    .mean()
    .to_frame('arr_delay')
    .reset_index()
    .head()
)

   year  month  day  arr_delay
0  2013      3    1      -14.0
1  2013      3    3       23.0
2  2013      3    4       12.0
3  2013      3    5        NaN
4  2013      3    6        NaN

> [!tip] You will find that in Pandas, the principle of TMTOWTDI &mdash; There's More Than One Way To Do It &mdash; applies.